# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - leg_controller

  leg_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - top_joint
      - top_leg_joint
      - bot_leg_joint
      - bot_rotative_joint
      - wheel_joint
    action_ns: follow_joint_trajectory
    default: true