controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz 
    use_sim_time: true

    leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

leg_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - top_joint
      - top_leg_joint
      - bot_leg_joint
      - bot_rotative_joint
      - wheel_joint